### ISSUE TITLE
docs: update readme for 2.0

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#443]
```[tasklist]
### Tasks
- [x] Update `Usage Notes` section to reflect updated platform support
- [x] Update all screenshots
- [x] Update sample code
```

This should be the _last_ thing done prior to 2.0 stable release
