### ISSUE TITLE
Refactor `PushButton` API surface for variant clarity

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#444]
According to the [Sonoma Figma Kit](https://www.figma.com/file/IX6ph2VWrJiRoMTI1Byz0K/Apple-Design-Resources---macOS-(Community)?node-id=121%3A11922&mode=dev), there are three variants of push buttons:
* primary
* secondary
* destructive

![Push Buttons](https://github.com/macosui/macos_ui/assets/4250470/194edd9c-627e-416f-a938-b7d0411fbb92)

## Styling Requirements:
* The background color of primary buttons should always be the system accent color _or_ the color set in `PushButtonThemeData`.
* The background color of secondary buttons should always be the default white/dark grey color unless overridden by `PushButtonThemeData`.
* The background color of destructive buttons should always be the default white/dark grey, and the button's text should always be styled to the shade of red appropriate for current theme. Destructive buttons should not respect the background color set by `PushButtonThemeData`.

## Implementation Steps
```[tasklist]
### Tasks
- [ ] Introduce `PushButtonVariant` enum
- [ ] Remove `color` property
- [ ] Remove `isSecondary` property
- [ ] Apply styling requirements
```
