### ISSUE TITLE
`PushButton` fidelity

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#445]
`PushButton` requires several fidelity improvements for parity with native push buttons

```[tasklist]
### Tasks
- [ ] Determine and apply the appropriate gradients, box shadows, padding, and border radii for all control sizes
- [ ] Determine and apply correct press animation
- [ ] Apply correct secondary background colors
- [ ] Apply correct disabled background colors
```
