### ISSUE TITLE
Update `MacosAlertDialog`

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#452]
```[tasklist]
### Tasks
- [ ] Add an optional help button in the top right
- [ ] Add an optional "cancel" button
- [ ] Allow up to four secondary buttons
- [ ] Ensure secondary and cancel buttons are not primary buttons
```
Reference: [Sonoma Figma Kit](https://www.figma.com/file/IX6ph2VWrJiRoMTI1Byz0K/Apple-Design-Resources---macOS-(Community)?node-id=121%3A11166&mode=dev)
